#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD Socket Server
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
PIDFILE=/var/run/aesdsocket.pid
NAME=aesdsocket

case "$1" in
  start)
    echo "Starting $NAME"
    start-stop-daemon --start --quiet --background \
      --make-pidfile --pidfile $PIDFILE \
      --exec $DAEMON
    ;;
  stop)
    echo "Stopping $NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
      PID=$(cat $PIDFILE)
      if ps -p $PID > /dev/null 2>&1; then
        echo "$NAME is running (pid $PID)"
        exit 0
      else
        echo "$NAME is not running but pid file exists"
        exit 1
      fi
    else
      echo "$NAME is not running"
      exit 3
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

